### ISSUE TITLE
Release cdc-source 1.0 M1

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/cdc-debezium#2]
Cleanup items:
- [x]  remove todo's from README
- [x]  remove standalone Boot steps from README
- [x]  revise properties to be more aligned with the cdc-source, naming-conventions wise
- [x]  Publish the M1 release to Spring's milestone repo

**Comment by fengkaijia** [comment]
Any ETA on the final release date?

**Comment by sabbyanandan** [comment]
Hi, @fengkaijia: We closed the issue when the associated cleanup PR was merged. However, we are yet to publish the M1 bits to the milestone repo still. I added another line-item to the description - we will release it hopefully this week.

The GA release is planned to go in the next release train release of the App Starters, though.

**Comment by sabbyanandan** [comment]
Hi, @fengkaijia. There's a 1.0 M1 available for use (see: [Kafka](https://repo.spring.io/libs-milestone/org/springframework/cloud/stream/app/cdc-debezium-source-kafka/1.0.0.M1/)/[Rabbit](https://repo.spring.io/libs-milestone/org/springframework/cloud/stream/app/cdc-debezium-source-rabbit/1.0.0.M1/)). Please try it out and let us know if you have any feedback.
